version: 1.0.{build}
image: Visual Studio 2017
build:
  verbosity: minimal
environment:
  my_variable:
    secure: /TWLGvacR15wTT4SOCd5Hg==
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
